# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from doclens.fingerprint.v1 import fingerprint_pb2 as doclens_dot_fingerprint_dot_v1_dot_fingerprint__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in doclens/fingerprint/v1/fingerprint_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FingerprintServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFingerprint = channel.unary_unary(
                '/doclens.fingerprint.v1.FingerprintService/GetFingerprint',
                request_serializer=doclens_dot_fingerprint_dot_v1_dot_fingerprint__pb2.GetFingerprintRequest.SerializeToString,
                response_deserializer=doclens_dot_fingerprint_dot_v1_dot_fingerprint__pb2.FingerprintResponse.FromString,
                _registered_method=True)
        self.FindDuplicates = channel.unary_unary(
                '/doclens.fingerprint.v1.FingerprintService/FindDuplicates',
                request_serializer=doclens_dot_fingerprint_dot_v1_dot_fingerprint__pb2.FindDuplicatesRequest.SerializeToString,
                response_deserializer=doclens_dot_fingerprint_dot_v1_dot_fingerprint__pb2.DuplicateResults.FromString,
                _registered_method=True)


class FingerprintServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetFingerprint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindDuplicates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FingerprintServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFingerprint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFingerprint,
                    request_deserializer=doclens_dot_fingerprint_dot_v1_dot_fingerprint__pb2.GetFingerprintRequest.FromString,
                    response_serializer=doclens_dot_fingerprint_dot_v1_dot_fingerprint__pb2.FingerprintResponse.SerializeToString,
            ),
            'FindDuplicates': grpc.unary_unary_rpc_method_handler(
                    servicer.FindDuplicates,
                    request_deserializer=doclens_dot_fingerprint_dot_v1_dot_fingerprint__pb2.FindDuplicatesRequest.FromString,
                    response_serializer=doclens_dot_fingerprint_dot_v1_dot_fingerprint__pb2.DuplicateResults.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'doclens.fingerprint.v1.FingerprintService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('doclens.fingerprint.v1.FingerprintService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FingerprintService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFingerprint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doclens.fingerprint.v1.FingerprintService/GetFingerprint',
            doclens_dot_fingerprint_dot_v1_dot_fingerprint__pb2.GetFingerprintRequest.SerializeToString,
            doclens_dot_fingerprint_dot_v1_dot_fingerprint__pb2.FingerprintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindDuplicates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doclens.fingerprint.v1.FingerprintService/FindDuplicates',
            doclens_dot_fingerprint_dot_v1_dot_fingerprint__pb2.FindDuplicatesRequest.SerializeToString,
            doclens_dot_fingerprint_dot_v1_dot_fingerprint__pb2.DuplicateResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
