# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: doclens/fingerprint/v1/fingerprint.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'doclens/fingerprint/v1/fingerprint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(doclens/fingerprint/v1/fingerprint.proto\x12\x16\x64oclens.fingerprint.v1\",\n\x15GetFingerprintRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\"h\n\x15\x46indDuplicatesRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0e\n\x06sha256\x18\x02 \x01(\t\x12\x0c\n\x04tlsh\x18\x03 \x01(\t\x12\r\n\x05phash\x18\x04 \x01(\t\x12\r\n\x05limit\x18\x05 \x01(\x05\"\xa7\x01\n\x0b\x46ingerprint\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x14\n\x0coriginal_ref\x18\x02 \x01(\t\x12\x16\n\x0enormalized_ref\x18\x03 \x01(\t\x12\x0e\n\x06sha256\x18\x04 \x01(\t\x12\x0c\n\x04tlsh\x18\x05 \x01(\t\x12\r\n\x05phash\x18\x06 \x01(\t\x12\x14\n\x0c\x64uplicate_of\x18\x07 \x01(\t\x12\x12\n\ncreated_at\x18\x08 \x01(\t\"O\n\x13\x46ingerprintResponse\x12\x38\n\x0b\x66ingerprint\x18\x01 \x01(\x0b\x32#.doclens.fingerprint.v1.Fingerprint\"\x7f\n\x0e\x44uplicateMatch\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x15\n\rtlsh_distance\x18\x02 \x01(\x05\x12\x16\n\x0ephash_distance\x18\x03 \x01(\x05\x12\x13\n\x0b\x65xact_match\x18\x04 \x01(\x08\x12\x14\n\x0c\x64uplicate_of\x18\x05 \x01(\t\"K\n\x10\x44uplicateResults\x12\x37\n\x07matches\x18\x01 \x03(\x0b\x32&.doclens.fingerprint.v1.DuplicateMatch2\xed\x01\n\x12\x46ingerprintService\x12l\n\x0eGetFingerprint\x12-.doclens.fingerprint.v1.GetFingerprintRequest\x1a+.doclens.fingerprint.v1.FingerprintResponse\x12i\n\x0e\x46indDuplicates\x12-.doclens.fingerprint.v1.FindDuplicatesRequest\x1a(.doclens.fingerprint.v1.DuplicateResultsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doclens.fingerprint.v1.fingerprint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETFINGERPRINTREQUEST']._serialized_start=68
  _globals['_GETFINGERPRINTREQUEST']._serialized_end=112
  _globals['_FINDDUPLICATESREQUEST']._serialized_start=114
  _globals['_FINDDUPLICATESREQUEST']._serialized_end=218
  _globals['_FINGERPRINT']._serialized_start=221
  _globals['_FINGERPRINT']._serialized_end=388
  _globals['_FINGERPRINTRESPONSE']._serialized_start=390
  _globals['_FINGERPRINTRESPONSE']._serialized_end=469
  _globals['_DUPLICATEMATCH']._serialized_start=471
  _globals['_DUPLICATEMATCH']._serialized_end=598
  _globals['_DUPLICATERESULTS']._serialized_start=600
  _globals['_DUPLICATERESULTS']._serialized_end=675
  _globals['_FINGERPRINTSERVICE']._serialized_start=678
  _globals['_FINGERPRINTSERVICE']._serialized_end=915
# @@protoc_insertion_point(module_scope)
